---
- name: Dynamically add host to inventory
  hosts: localhost
  sudo: no
  tasks:
    - name: Group by provisioner type
      group_by: key={{ provisioner.type }}

    - name: Add the host to the inventory
      when: installer.type in ['rdo-manager']
      add_host:
        name="host0"
        groups="provisioned"
        ansible_fqdn="{{ lookup('env', 'TEST_MACHINE') }}"
        ansible_ssh_user="{{ provisioner.remote_user }}"
        ansible_ssh_private_key_file="{{ provisioner.key_file }}"
        ansible_ssh_host="{{ lookup('env', 'TEST_MACHINE') }}"
