---
- name: disable gpgcheck for rdo for every non production repo
  lineinfile:
    dest=/etc/yum.repos.d/rdo-release.repo
    regexp=^gpgcheck=1
    line=gpgcheck=0
  when: product.repo_type != 'production'

- name: Create the upstream delorean repositories for EPEL RDO
  get_url: url="{{ product.repo['delorean'][ansible_distribution][ansible_distribution_version] }}/current/{{ product.repo.delorean.repo_file }}"
            dest=/etc/yum.repos.d/rdo-trunk-release.repo
            mode=0644
  notify:
    - Yum clean all
  when: product.repo_type in ['delorean', 'delorean_mgt'] and product.repo.delorean_pin_version is not defined

- name: Create the upstream delorean dependency repositories for EPEL RDO
  get_url: url="{{ product.repo['delorean'][ansible_distribution][ansible_distribution_version] }}/{{ product.repo.delorean_deps.repo_file }}"
            dest=/etc/yum.repos.d/rdo-trunk-release-deps.repo
            mode=0644
  notify:
    - Yum clean all
  when: product.repo_type in ['delorean', 'delorean_mgt'] and product.repo.delorean_deps is defined

- name: Create the pinned upstream delorean repositories for EPEL RDO
  get_url: url="{{ product.repo['delorean'][ansible_distribution][ansible_distribution_version] }}/{{product.repo.delorean_pin_version}}/{{ product.repo.delorean.repo_file }}"
            dest=/etc/yum.repos.d/rdo-trunk-release.repo
            mode=0644
  notify:
    - Yum clean all
  when: product.repo_type in ['delorean', 'delorean_mgt'] and product.repo.delorean_pin_version is defined

- name: Create the upstream delorean mgt repositories for EPEL RDO
  get_url: url="{{ product.repo['delorean_mgt'][ansible_distribution][ansible_distribution_version] }}/current/delorean-rdo-management.repo"
            dest=/etc/yum.repos.d/rdo-mgt-trunk-release.repo
            mode=0644
  notify:
    - Yum clean all
  when: product.repo_type in ['delorean_mgt_only','delorean_mgt'] and product.repo.delorean_mgt_pin_version is not defined

- name: Create the pinned upstream delorean mgt repositories for EPEL RDO
  get_url: url="{{ product.repo['delorean_mgt'][ansible_distribution][ansible_distribution_version] }}"/"{{product.repo.delorean_mgt_pin_version}}"/delorean-rdo-management.repo
            dest=/etc/yum.repos.d/rdo-mgt-trunk-release.repo
            mode=0644
  notify:
    - Yum clean all
  when: product.repo_type in ['delorean_mgt_only','delorean_mgt'] and product.repo.delorean_mgt_pin_version is defined

- name: update yum priority of rdo trunk repo
  shell: "sed -i 's/priority=1/priority=10/' /etc/yum.repos.d/rdo-trunk-release.repo"
  sudo: yes
  when: product.repo_type in ['delorean', 'delorean_mgt']

- name: List available yum repositories
  command: yum -d 9 repolist
  register: result

- name: Print repolist
  debug: var=result.stdout_lines
